### ISSUE TITLE
The plugin doesn't update <select> element's value.

### ISSUE THREAD

**Issue by dytyniuk** [ikalnytskyi/listbox.js#2]
Hi.

We have just faced with the following minor issue: the plugin doesn't update binded `<select>` element's value when user selects an option in the listbox.

Yes, it sets `selected` attribute to the corresponding `<option>` element, but not to the `<select>`. So, JavaScript handlers which have been assigned to `<select>` `change` event aren't triggered.

A standard behavior is:

``` html
<select id="test" name="test">
    <option value="1">Option 1</option>
    <option value="2">Option 2</option>
    <option value="3">Option 3</option>
    <option value="4">Option 4</option>
    <option value="5">Option 5</option>
</select> 
```

``` javascript
$(function(){
    $('#test').on('change', function() {
        console.log($(this).val());
    });
});
```

So if you have selected an option, there will be an updated value in the console output.

Provided `change` event handler doesn't being triggered when you have changed your selection in the listbox.

I've just forked your plugin. I can provide a pull request in the evening. I think.
Or, if you would like to, I can post a diff in the issue comment.

Regards, Ievgenii.

**Comment by ikalnytskyi** [comment]
Thanks for bug report. :)

**Comment by dytyniuk** [comment]
Good evening :)

Thanks for your attention. We tried to place a line of code you have just committed, but it didn't help.
We had to do the next way:

``` javascript
Listbox.prototype._selectItem = function (item) {
    item.attr('selected', 'selected');

    // make changes in real list
    var selectItem = this._parent.children().get(item.index());
    $(selectItem).attr('selected', '');
    this._parent.val($(selectedItem).val()).trigger('change');
}
```

And it worked. Anyway, thank you for you plugin.

Have a nice evening. Regards, Ievgenii.

**Comment by ikalnytskyi** [comment]
Hi,

Hm.. My solution works fine in Chrome 29. Maybe it's a browser-depended code? Anyway, I definetely must add unit tests to control such situations.
