### ISSUE TITLE
Keep item values

### ISSUE THREAD

**Issue by James8192** [ikalnytskyi/listbox.js#5]
listbox.js Line #176

was:

``` JavaScript
            .text(parentItem.text())
            .click(function () {
```

became:

``` JavaScript
            .text(parentItem.text())
            .val(parentItem.val())
            .click(function () {
```

**Comment by ikalnytskyi** [comment]
Hello,

I'm not familiar with JavaScript, so could you please tell me why we need this?
As far as I understand, a `<div>` element has no `val()` method.

**Comment by James8192** [comment]
This is for comboboxes with associated values, for example:

``` html
<SELECT>
 <OPTION value="1">Text #1</OPTION>
 <OPTION value="2">Text #2</OPTION>
 <OPTION value="3">Text #3</OPTION>
 <OPTION value="4">Text #4</OPTION>
</SELECT>
```

**Comment by ikalnytskyi** [comment]
@James8192, it's make sense to have `value` attribute in `<option>`, but I see no need to have it in the `<div>`. Do you have some bug with it? Could you please provide more information if so?
