### ISSUE TITLE
How to deselect the multiple selected options?)

### ISSUE THREAD

**Issue by gencher** [ikalnytskyi/listbox.js#7]
My question is simple, I just couldn't reset(deselect) the selected options with a button. So any help?)

```
$(function () {
	$('select#packages').listbox({'searchbar': true});
		$('#sendBtn').click(function() {
			var obj = $('#packages option:selected');
				$.each( obj, function( key, value ) {
					$('#textarea').append(value.text + "  \n");
				});
			$('#packagesModal').modal('hide');
		});
});
```

This code works but I need to reset selections with #sendBtn because in the next times it all comes selected..

**Comment by ikalnytskyi** [comment]
Hey @gencher,

Thanks for reaching out to me and sorry for so the delay in my response. I have bad news for you: it's impossible to *reset* things. jQuery does not allow you to expose plugin's internal API to end users. However, if your end goal is to remove *all* selections from a given listbox, you can achieve this by the following workaround:

```javascript
// create a listbox with a custom "class" so we can distinguish this listbox instance from others
$('select#planets').listbox({'class': 'planets'}); 

$('button#reset').click(function() {
  // iterate over all listbox items and unselect (click) if it's selected
  $('.lbjs.planets .lbjs-list').children().each(function () {
    if ($(this).attr('selected')) {
      $(this).click();
    }
  });
});
```
